'use client';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {ArrowDown,ArrowUpRight,ArrowUp,Download,Fish,Move3D,RotateCcw,Anchor,Check,LoaderCircle} from 'lucide-react';
import {createFishingScene} from './fishing-scene';

const chapters=[
 {id:'ember',name:'Ember',sub:'Hallgatók, oktatók',title:<>Nem mindenki<br/>ugyanarra <em>harap.</em></>,color:'#526549',aside:'Egy tóban úszunk. Csak néha más tájékoztatást kapunk.',items:['Hiányos tájékozottság','Eltérő elvárások (hallgatók – oktatók)','Késői jelentkezés','Alacsony digitális kompetencia']},
 {id:'folyamatok',name:'Folyamatok',sub:'Eljárások, szabályok',title:<>Ezen a zsinóron<br/>akad néhány <em>csomó.</em></>,color:'#778050',aside:'A „még egy kattintás” itt hagyományosan hét kattintást jelent.',items:['Bonyolult, nem egyértelmű kurzusfelvételi eljárás','Nem átlátható előfeltételek','Rugalmatlan módosítási lehetőségek','Sok manuális lépés']},
 {id:'eszkozok',name:'Eszközök',sub:'Rendszerek, infrastruktúra',title:<>A felszerelés is<br/>tud <em>akasztani.</em></>,color:'#38695f',aside:'Neptun a vizek ura. Néha a várakozási időé is.',items:['Különálló rendszerek (pl. Neptun, Moodle)','Lassú, gyakori rendszerhibák','Nem felhasználóbarát felület','Hiányos valós idejű információk']},
 {id:'kornyezet',name:'Külső környezet',sub:'Szabályozás, egyéb tényezők',title:<>Szűk a tó.<br/>Sok a <em>horgász.</em></>,color:'#a18250',aside:'A tanterem sajnos attól még nem lesz nagyobb, hogy frissítjük az oldalt.',items:['Gyakori szabályváltozások','Szűkös terem- és kapacitáskeretek','Intézményi előírások, határidők','Rövid féléves időszak']},
 {id:'szervezet',name:'Szervezet',sub:'Kommunikáció, struktúra',title:<>Ki fogja<br/>a zsinór <em>végét?</em></>,color:'#775d40',aside:'A „nem hozzánk tartozik” nem egy külön tanszék.',items:['Nem egységes tájékoztatás','Lassú, nehezen elérhető ügyintézés','Hiányos belső kommunikáció','Nem világos felelősségi körök']}
];
const stops=['felszin','kapas',...chapters.map(c=>c.id),'osszefuggesek','hazavitel'];
type SceneAPI=ReturnType<typeof createFishingScene>;
export default function FishingStory(){
 const host=useRef<HTMLDivElement>(null),api=useRef<SceneAPI|null>(null),page=useRef<HTMLDivElement>(null);
 const [percent,setPercent]=useState(0),[error,setError]=useState(false),[step,setStep]=useState(0),[free,setFree]=useState(false),[download,setDownload]=useState(''),[shared,setShared]=useState(false);
 const ready=percent===100;
 useEffect(()=>{if(!host.current)return;let disposed=false;try{api.current=createFishingScene(host.current,p=>{if(!disposed){setPercent(p);if(p===100)setError(false);}},()=>{if(!disposed)setError(true);});}catch{queueMicrotask(()=>{if(!disposed)setError(true);});}
  const update=()=>{const positions=stops.map(s=>document.getElementById(s)?.offsetTop??0);let index=0;while(index<8&&scrollY>=positions[index+1]-1)index++;const progress=Math.min(8,index+(scrollY-positions[index])/Math.max(1,(positions[index+1]??positions[index]+innerHeight)-positions[index]));api.current?.update(progress);setStep(Math.min(8,Math.max(0,Math.round(progress))));page.current?.style.setProperty('--progress',String(progress/8));};
  window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);update();return()=>{disposed=true;window.removeEventListener('scroll',update);window.removeEventListener('resize',update);api.current?.dispose();api.current=null;};
 },[]);
 useEffect(()=>{if(step!==7&&free){queueMicrotask(()=>{api.current?.interact(false);setFree(false);});}},[step,free]);
 useEffect(()=>{type Tool={name:string;description:string;inputSchema:object;annotations:object;execute:(v:unknown)=>Promise<object>};const context=(document as Document&{modelContext?:{registerTool:(t:Tool,o:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool||!ready)return;const life=new AbortController();
  const tool:Tool={name:'navigate_fishing_story',description:'Navigate to one named chapter of the fishing story and return its rendered 3D scene state.',inputSchema:{type:'object',properties:{chapter:{type:'string',enum:stops}},required:['chapter'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(value){if(!value||typeof value!=='object'||Array.isArray(value))throw new TypeError('Expected an object');const obj=value as Record<string,unknown>;if(Object.keys(obj).length!==1||typeof obj.chapter!=='string'||!stops.includes(obj.chapter))throw new TypeError('Unknown chapter');document.getElementById(obj.chapter)?.scrollIntoView({behavior:'instant'});api.current?.update(stops.indexOf(obj.chapter),true);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return{chapter:obj.chapter,...api.current?.snapshot()};}};try{void Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();
 },[ready]);
 async function downloadObj(){if(download&&!download.includes('Újra'))return;try{setDownload('Csomag előkészítése…');const r=await fetch('/downloads/obj-manifest.json');if(!r.ok)throw Error();const m=await r.json() as{parts:string[];bytes:number};if(!Array.isArray(m.parts)||!m.parts.every(p=>/^hal-obj-\d{2}\.part$/.test(p)))throw Error();const chunks:Blob[]=[];for(let i=0;i<m.parts.length;i++){setDownload(`Letöltés · ${Math.round(i/m.parts.length*100)}%`);const part=await fetch('/downloads/'+m.parts[i]);if(!part.ok)throw Error();chunks.push(await part.blob());}const blob=new Blob(chunks,{type:'application/zip'});if(blob.size!==m.bytes)throw Error();const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Hal_3D_OBJ.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);setDownload('');}catch{setDownload('Újra megpróbálom');}}
 async function share(){try{await navigator.clipboard.writeText(location.origin);setShared(true);setTimeout(()=>setShared(false),2500);}catch{setShared(false);}}
 return <div className={'fishing-story'+(free?' free-view':'')} ref={page}>
  <a className="skip-link" href="#ember">Ugrás az okokhoz</a>
  <div className="landscape" ref={host} aria-hidden={!free}/>
  <div className="paper-grain" aria-hidden="true"/>
  {error&&<Image className="fish-fallback" src="/images/Hal_feliratokkal.png" width={3840} height={2720} alt="A teljes 3D hal az eredeti magyar feliratokkal" unoptimized/>}
  <header className="story-header"><a className="story-brand" href="#felszin"><Fish strokeWidth={1.4}/><span>KurzusKáosz<span className="brand-small">KIFOGJUK AZ OKOKAT.</span></span></a><span className="header-note">ISHIKAWA, EGY KICSIT MÁSKÉPP</span><a className="header-link" href="#osszefuggesek">A teljes fogás<ArrowUpRight size={17}/></a></header>
  <nav className="chapter-nav" aria-label="A horgászat állomásai">{stops.slice(0,8).map((s,i)=><a key={s} href={'#'+s} className={step===i?'current':''} aria-label={i<2?i===0?'A felszín alatt':'Kapás':i<7?chapters[i-2].name:'A teljes diagram'} aria-current={step===i?'step':undefined}><span>{i<2?i===0?'Felszín':'Kapás':i<7?chapters[i-2].name:'A fogás'}</span><i/></a>)}</nav>
  <div className="story-status"><span className="status-dot"/><span>{!ready&&!error?`Csali előkészítése · ${percent}%`:error?'A 3D nézet helyett a render látható':free?'Most te forgatod a fogást.':step===0?'A tó nyugodt. Egyelőre.':step===1?'Kapás! Tartsd a zsinórt.':step<7?`${step-1} / 5 okcsoport a felszínen`:step===7?'Megvan a teljes kép.':'Ezt a fogást hazaviheted.'}</span></div>
  <div className="scroll-track" aria-hidden="true"><div/></div>
  <section className="story-section hero" id="felszin"><div className="section-copy"><p className="eyebrow"><span/> EGY KURZUSFELVÉTEL MÉLYÉRE NÉZÜNK</p><h1>Kapás van.<br/><em>Kurzus</em><br/>még nincs.</h1><p className="hero-intro">A felszínen csak a káosz látszik.<br/>Húzzuk ki együtt, ami mögötte van.</p><a className="round-cta" href="#kapas"><span><ArrowDown size={21}/></span>Görgess, és húzd ki</a></div><div className="field-note"><span className="handwritten">Itt valami nagyon<br/>ráharapott a problémára.</span><svg viewBox="0 0 100 75" aria-hidden="true"><path d="M4 5Q85-5 82 64m-12-9 12 10 9-14"/></svg></div><div className="hero-bottom"><span>01 — A FELSZÍN ALATT</span><span>5 OKCSOPORT · 20 OK · 1 NAGY GUBANC</span></div></section>
  <section className="story-section catch-section" id="kapas"><div className="section-copy"><p className="eyebrow">MÁR MOZOG AZ ÚSZÓ</p><h2>Nem a hal nagy.<br/>A <em>gubanc.</em></h2><p className="lead">A nehézkes kurzusfelvétel ritkán egyetlen hibán múlik. A problémát több, egymáshoz kapcsolódó ok húzza lefelé.</p><p className="quiet-note"><Anchor size={18}/>Az Ishikawa-diagram ezeket az okokat teszi láthatóvá.</p></div><span className="water-word" aria-hidden="true">hóóó-rukk.</span></section>
  {chapters.map((c,i)=><section className={'story-section cause-section cause-'+i} id={c.id} key={c.id} style={{'--category':c.color} as React.CSSProperties}><article className="section-copy cause-copy"><p className="eyebrow"><span className="chapter-number">0{i+1}</span>{c.name.toLocaleUpperCase('hu-HU')}</p><h2>{c.title}</h2><p className="category-sub">{c.sub}</p><ul className="cause-list">{c.items.map((item,j)=><li key={item}><span>0{j+1}</span>{item}</li>)}</ul><p className="fishing-aside">{c.aside}</p></article></section>)}
  <section className="story-section complete-section" id="osszefuggesek"><div className="complete-heading"><p className="eyebrow">MEGVAN A TELJES FOGÁS</p><h2>Így áll össze a <em>kép.</em></h2><p>Zavaros, nehézkes kurzusfelvétel — öt oldalról megvilágítva.</p></div><div className="explore-controls"><button className={free?'active':''} disabled={!ready} onClick={()=>{api.current?.interact(!free);setFree(!free);}}><Move3D size={19}/>{free?'Forgatás kikapcsolása':'Szabadon forgatom'}</button><button disabled={!ready} onClick={()=>{api.current?.reset();setFree(false);}} aria-label="Alaphelyzet"><RotateCcw size={18}/></button><a href="#hazavitel">Hazaviszem<ArrowDown size={17}/></a></div></section>
  <section className="story-section take-home" id="hazavitel"><div className="take-home-card"><div className="catch-stamp"><Fish size={36} strokeWidth={1.2}/><span>FENNTARTHATÓ FOGÁS<br/>AZ ÖSSZES OK MEGMARADT</span></div><p className="eyebrow">A FELISMERÉS AZ ELSŐ JÓ KAPÁS</p><h2>A halat vissza.<br/>A tanulságot <em>haza.</em></h2><p>Öt okcsoport, húsz ok és az eredeti ábra minden felirata. Vidd tovább a térbeli modellt, vagy oszd meg a horgászatot.</p><div className="take-home-actions"><button className="primary-action" onClick={()=>void downloadObj()} disabled={!!download&&!download.includes('Újra')}>{download?<LoaderCircle size={19}/>:<Download size={19}/>}<span>{download||'A 3D modell letöltése'}</span></button><button className="text-action" onClick={()=>void share()}>{shared?<Check size={17}/>:<ArrowUpRight size={17}/>} {shared?'Link másolva':'A horgászat megosztása'}</button></div><div className="file-links"><a href="/images/Hal_feliratokkal.png" download>Feliratos PNG<ArrowUpRight size={14}/></a><a href="/images/Hal_3D_atlatszo.png" download>Csak a hal, PNG<ArrowUpRight size={14}/></a><Link href="/modell">A modellnézegető<ArrowUpRight size={14}/></Link></div><p className="small-print">OBJ + anyagok + 4K textúra · A hal: 3 676 000 háromszög<br/>A hal művészi rekonstrukció; a feliratok tényleges térbeli betűk.</p></div><footer className="story-footer"><a href="#felszin">Vissza a vízpartra<ArrowUp size={16}/></a><span>KurzusKáosz Kft. · Ishikawa a vízparton</span><a href="https://github.com/MKristof64/kurzuskaosz-horgaszat" target="_blank" rel="noreferrer">GitHub<ArrowUpRight size={16}/></a></footer></section>
 </div>;
}
